/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAcademicsRouteImport } from './routes/_authenticated/academics'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedCareerRouteImport } from './routes/_authenticated/career'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCompanySkillDemandRouteImport } from './routes/_authenticated/company-skill-demand'
import { Route as AuthenticatedCourseHealthRouteImport } from './routes/_authenticated/course-health'
import { Route as AuthenticatedCurriculumAlignmentRouteImport } from './routes/_authenticated/curriculum-alignment'
import { Route as AuthenticatedCurriculumRecommendationsRouteImport } from './routes/_authenticated/curriculum-recommendations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDistrictSkillMapRouteImport } from './routes/_authenticated/district-skill-map'
import { Route as AuthenticatedDistrictTrainingPlannerRouteImport } from './routes/_authenticated/district-training-planner'
import { Route as AuthenticatedEmergingSkillsRouteImport } from './routes/_authenticated/emerging-skills'
import { Route as AuthenticatedEmployerValidationRouteImport } from './routes/_authenticated/employer-validation'
import { Route as AuthenticatedIndustrySurveysRouteImport } from './routes/_authenticated/industry-surveys'
import { Route as AuthenticatedInfrastructurePlanningRouteImport } from './routes/_authenticated/infrastructure-planning'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedLabourMarketRouteImport } from './routes/_authenticated/labour-market'
import { Route as AuthenticatedLocationDemandRouteImport } from './routes/_authenticated/location-demand'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedPlacementFeedbackRouteImport } from './routes/_authenticated/placement-feedback'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedQualificationMappingRouteImport } from './routes/_authenticated/qualification-mapping'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedRoleDemandRouteImport } from './routes/_authenticated/role-demand'
import { Route as AuthenticatedSkillIntelligenceRouteImport } from './routes/_authenticated/skill-intelligence'
import { Route as AuthenticatedTrainerIntelligenceRouteImport } from './routes/_authenticated/trainer-intelligence'
import { Route as AuthenticatedTrainingCapacityRouteImport } from './routes/_authenticated/training-capacity'
import { Route as AuthenticatedCompaniesSlugRouteImport } from './routes/_authenticated/companies.$slug'
import { Route as AuthenticatedCompaniesManageRouteImport } from './routes/_authenticated/companies.manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcademicsRoute = AuthenticatedAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareerRoute = AuthenticatedCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanySkillDemandRoute =
  AuthenticatedCompanySkillDemandRouteImport.update({
    id: '/company-skill-demand',
    path: '/company-skill-demand',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCourseHealthRoute =
  AuthenticatedCourseHealthRouteImport.update({
    id: '/course-health',
    path: '/course-health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumAlignmentRoute =
  AuthenticatedCurriculumAlignmentRouteImport.update({
    id: '/curriculum-alignment',
    path: '/curriculum-alignment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCurriculumRecommendationsRoute =
  AuthenticatedCurriculumRecommendationsRouteImport.update({
    id: '/curriculum-recommendations',
    path: '/curriculum-recommendations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistrictSkillMapRoute =
  AuthenticatedDistrictSkillMapRouteImport.update({
    id: '/district-skill-map',
    path: '/district-skill-map',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDistrictTrainingPlannerRoute =
  AuthenticatedDistrictTrainingPlannerRouteImport.update({
    id: '/district-training-planner',
    path: '/district-training-planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmergingSkillsRoute =
  AuthenticatedEmergingSkillsRouteImport.update({
    id: '/emerging-skills',
    path: '/emerging-skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployerValidationRoute =
  AuthenticatedEmployerValidationRouteImport.update({
    id: '/employer-validation',
    path: '/employer-validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndustrySurveysRoute =
  AuthenticatedIndustrySurveysRouteImport.update({
    id: '/industry-surveys',
    path: '/industry-surveys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInfrastructurePlanningRoute =
  AuthenticatedInfrastructurePlanningRouteImport.update({
    id: '/infrastructure-planning',
    path: '/infrastructure-planning',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLabourMarketRoute =
  AuthenticatedLabourMarketRouteImport.update({
    id: '/labour-market',
    path: '/labour-market',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocationDemandRoute =
  AuthenticatedLocationDemandRouteImport.update({
    id: '/location-demand',
    path: '/location-demand',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlacementFeedbackRoute =
  AuthenticatedPlacementFeedbackRouteImport.update({
    id: '/placement-feedback',
    path: '/placement-feedback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQualificationMappingRoute =
  AuthenticatedQualificationMappingRouteImport.update({
    id: '/qualification-mapping',
    path: '/qualification-mapping',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoleDemandRoute = AuthenticatedRoleDemandRouteImport.update({
  id: '/role-demand',
  path: '/role-demand',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillIntelligenceRoute =
  AuthenticatedSkillIntelligenceRouteImport.update({
    id: '/skill-intelligence',
    path: '/skill-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainerIntelligenceRoute =
  AuthenticatedTrainerIntelligenceRouteImport.update({
    id: '/trainer-intelligence',
    path: '/trainer-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingCapacityRoute =
  AuthenticatedTrainingCapacityRouteImport.update({
    id: '/training-capacity',
    path: '/training-capacity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesSlugRoute =
  AuthenticatedCompaniesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCompaniesManageRoute =
  AuthenticatedCompaniesManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academics': typeof AuthenticatedAcademicsRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/career': typeof AuthenticatedCareerRoute
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/company-skill-demand': typeof AuthenticatedCompanySkillDemandRoute
  '/course-health': typeof AuthenticatedCourseHealthRoute
  '/curriculum-alignment': typeof AuthenticatedCurriculumAlignmentRoute
  '/curriculum-recommendations': typeof AuthenticatedCurriculumRecommendationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/district-skill-map': typeof AuthenticatedDistrictSkillMapRoute
  '/district-training-planner': typeof AuthenticatedDistrictTrainingPlannerRoute
  '/emerging-skills': typeof AuthenticatedEmergingSkillsRoute
  '/employer-validation': typeof AuthenticatedEmployerValidationRoute
  '/industry-surveys': typeof AuthenticatedIndustrySurveysRoute
  '/infrastructure-planning': typeof AuthenticatedInfrastructurePlanningRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/labour-market': typeof AuthenticatedLabourMarketRoute
  '/location-demand': typeof AuthenticatedLocationDemandRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/placement-feedback': typeof AuthenticatedPlacementFeedbackRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qualification-mapping': typeof AuthenticatedQualificationMappingRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/role-demand': typeof AuthenticatedRoleDemandRoute
  '/skill-intelligence': typeof AuthenticatedSkillIntelligenceRoute
  '/trainer-intelligence': typeof AuthenticatedTrainerIntelligenceRoute
  '/training-capacity': typeof AuthenticatedTrainingCapacityRoute
  '/companies/$slug': typeof AuthenticatedCompaniesSlugRoute
  '/companies/manage': typeof AuthenticatedCompaniesManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academics': typeof AuthenticatedAcademicsRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/career': typeof AuthenticatedCareerRoute
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/company-skill-demand': typeof AuthenticatedCompanySkillDemandRoute
  '/course-health': typeof AuthenticatedCourseHealthRoute
  '/curriculum-alignment': typeof AuthenticatedCurriculumAlignmentRoute
  '/curriculum-recommendations': typeof AuthenticatedCurriculumRecommendationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/district-skill-map': typeof AuthenticatedDistrictSkillMapRoute
  '/district-training-planner': typeof AuthenticatedDistrictTrainingPlannerRoute
  '/emerging-skills': typeof AuthenticatedEmergingSkillsRoute
  '/employer-validation': typeof AuthenticatedEmployerValidationRoute
  '/industry-surveys': typeof AuthenticatedIndustrySurveysRoute
  '/infrastructure-planning': typeof AuthenticatedInfrastructurePlanningRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/labour-market': typeof AuthenticatedLabourMarketRoute
  '/location-demand': typeof AuthenticatedLocationDemandRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/placement-feedback': typeof AuthenticatedPlacementFeedbackRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qualification-mapping': typeof AuthenticatedQualificationMappingRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/role-demand': typeof AuthenticatedRoleDemandRoute
  '/skill-intelligence': typeof AuthenticatedSkillIntelligenceRoute
  '/trainer-intelligence': typeof AuthenticatedTrainerIntelligenceRoute
  '/training-capacity': typeof AuthenticatedTrainingCapacityRoute
  '/companies/$slug': typeof AuthenticatedCompaniesSlugRoute
  '/companies/manage': typeof AuthenticatedCompaniesManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/academics': typeof AuthenticatedAcademicsRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/career': typeof AuthenticatedCareerRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/company-skill-demand': typeof AuthenticatedCompanySkillDemandRoute
  '/_authenticated/course-health': typeof AuthenticatedCourseHealthRoute
  '/_authenticated/curriculum-alignment': typeof AuthenticatedCurriculumAlignmentRoute
  '/_authenticated/curriculum-recommendations': typeof AuthenticatedCurriculumRecommendationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/district-skill-map': typeof AuthenticatedDistrictSkillMapRoute
  '/_authenticated/district-training-planner': typeof AuthenticatedDistrictTrainingPlannerRoute
  '/_authenticated/emerging-skills': typeof AuthenticatedEmergingSkillsRoute
  '/_authenticated/employer-validation': typeof AuthenticatedEmployerValidationRoute
  '/_authenticated/industry-surveys': typeof AuthenticatedIndustrySurveysRoute
  '/_authenticated/infrastructure-planning': typeof AuthenticatedInfrastructurePlanningRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/labour-market': typeof AuthenticatedLabourMarketRoute
  '/_authenticated/location-demand': typeof AuthenticatedLocationDemandRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/placement-feedback': typeof AuthenticatedPlacementFeedbackRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/qualification-mapping': typeof AuthenticatedQualificationMappingRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/role-demand': typeof AuthenticatedRoleDemandRoute
  '/_authenticated/skill-intelligence': typeof AuthenticatedSkillIntelligenceRoute
  '/_authenticated/trainer-intelligence': typeof AuthenticatedTrainerIntelligenceRoute
  '/_authenticated/training-capacity': typeof AuthenticatedTrainingCapacityRoute
  '/_authenticated/companies/$slug': typeof AuthenticatedCompaniesSlugRoute
  '/_authenticated/companies/manage': typeof AuthenticatedCompaniesManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/academics'
    | '/applications'
    | '/career'
    | '/companies'
    | '/company-skill-demand'
    | '/course-health'
    | '/curriculum-alignment'
    | '/curriculum-recommendations'
    | '/dashboard'
    | '/district-skill-map'
    | '/district-training-planner'
    | '/emerging-skills'
    | '/employer-validation'
    | '/industry-surveys'
    | '/infrastructure-planning'
    | '/intelligence'
    | '/labour-market'
    | '/location-demand'
    | '/mentor'
    | '/opportunities'
    | '/placement-feedback'
    | '/profile'
    | '/qualification-mapping'
    | '/resume'
    | '/role-demand'
    | '/skill-intelligence'
    | '/trainer-intelligence'
    | '/training-capacity'
    | '/companies/$slug'
    | '/companies/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/academics'
    | '/applications'
    | '/career'
    | '/companies'
    | '/company-skill-demand'
    | '/course-health'
    | '/curriculum-alignment'
    | '/curriculum-recommendations'
    | '/dashboard'
    | '/district-skill-map'
    | '/district-training-planner'
    | '/emerging-skills'
    | '/employer-validation'
    | '/industry-surveys'
    | '/infrastructure-planning'
    | '/intelligence'
    | '/labour-market'
    | '/location-demand'
    | '/mentor'
    | '/opportunities'
    | '/placement-feedback'
    | '/profile'
    | '/qualification-mapping'
    | '/resume'
    | '/role-demand'
    | '/skill-intelligence'
    | '/trainer-intelligence'
    | '/training-capacity'
    | '/companies/$slug'
    | '/companies/manage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/academics'
    | '/_authenticated/applications'
    | '/_authenticated/career'
    | '/_authenticated/companies'
    | '/_authenticated/company-skill-demand'
    | '/_authenticated/course-health'
    | '/_authenticated/curriculum-alignment'
    | '/_authenticated/curriculum-recommendations'
    | '/_authenticated/dashboard'
    | '/_authenticated/district-skill-map'
    | '/_authenticated/district-training-planner'
    | '/_authenticated/emerging-skills'
    | '/_authenticated/employer-validation'
    | '/_authenticated/industry-surveys'
    | '/_authenticated/infrastructure-planning'
    | '/_authenticated/intelligence'
    | '/_authenticated/labour-market'
    | '/_authenticated/location-demand'
    | '/_authenticated/mentor'
    | '/_authenticated/opportunities'
    | '/_authenticated/placement-feedback'
    | '/_authenticated/profile'
    | '/_authenticated/qualification-mapping'
    | '/_authenticated/resume'
    | '/_authenticated/role-demand'
    | '/_authenticated/skill-intelligence'
    | '/_authenticated/trainer-intelligence'
    | '/_authenticated/training-capacity'
    | '/_authenticated/companies/$slug'
    | '/_authenticated/companies/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academics': {
      id: '/_authenticated/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AuthenticatedAcademicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career': {
      id: '/_authenticated/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof AuthenticatedCareerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company-skill-demand': {
      id: '/_authenticated/company-skill-demand'
      path: '/company-skill-demand'
      fullPath: '/company-skill-demand'
      preLoaderRoute: typeof AuthenticatedCompanySkillDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course-health': {
      id: '/_authenticated/course-health'
      path: '/course-health'
      fullPath: '/course-health'
      preLoaderRoute: typeof AuthenticatedCourseHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum-alignment': {
      id: '/_authenticated/curriculum-alignment'
      path: '/curriculum-alignment'
      fullPath: '/curriculum-alignment'
      preLoaderRoute: typeof AuthenticatedCurriculumAlignmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculum-recommendations': {
      id: '/_authenticated/curriculum-recommendations'
      path: '/curriculum-recommendations'
      fullPath: '/curriculum-recommendations'
      preLoaderRoute: typeof AuthenticatedCurriculumRecommendationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/district-skill-map': {
      id: '/_authenticated/district-skill-map'
      path: '/district-skill-map'
      fullPath: '/district-skill-map'
      preLoaderRoute: typeof AuthenticatedDistrictSkillMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/district-training-planner': {
      id: '/_authenticated/district-training-planner'
      path: '/district-training-planner'
      fullPath: '/district-training-planner'
      preLoaderRoute: typeof AuthenticatedDistrictTrainingPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emerging-skills': {
      id: '/_authenticated/emerging-skills'
      path: '/emerging-skills'
      fullPath: '/emerging-skills'
      preLoaderRoute: typeof AuthenticatedEmergingSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employer-validation': {
      id: '/_authenticated/employer-validation'
      path: '/employer-validation'
      fullPath: '/employer-validation'
      preLoaderRoute: typeof AuthenticatedEmployerValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/industry-surveys': {
      id: '/_authenticated/industry-surveys'
      path: '/industry-surveys'
      fullPath: '/industry-surveys'
      preLoaderRoute: typeof AuthenticatedIndustrySurveysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/infrastructure-planning': {
      id: '/_authenticated/infrastructure-planning'
      path: '/infrastructure-planning'
      fullPath: '/infrastructure-planning'
      preLoaderRoute: typeof AuthenticatedInfrastructurePlanningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labour-market': {
      id: '/_authenticated/labour-market'
      path: '/labour-market'
      fullPath: '/labour-market'
      preLoaderRoute: typeof AuthenticatedLabourMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/location-demand': {
      id: '/_authenticated/location-demand'
      path: '/location-demand'
      fullPath: '/location-demand'
      preLoaderRoute: typeof AuthenticatedLocationDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/placement-feedback': {
      id: '/_authenticated/placement-feedback'
      path: '/placement-feedback'
      fullPath: '/placement-feedback'
      preLoaderRoute: typeof AuthenticatedPlacementFeedbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qualification-mapping': {
      id: '/_authenticated/qualification-mapping'
      path: '/qualification-mapping'
      fullPath: '/qualification-mapping'
      preLoaderRoute: typeof AuthenticatedQualificationMappingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/role-demand': {
      id: '/_authenticated/role-demand'
      path: '/role-demand'
      fullPath: '/role-demand'
      preLoaderRoute: typeof AuthenticatedRoleDemandRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-intelligence': {
      id: '/_authenticated/skill-intelligence'
      path: '/skill-intelligence'
      fullPath: '/skill-intelligence'
      preLoaderRoute: typeof AuthenticatedSkillIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trainer-intelligence': {
      id: '/_authenticated/trainer-intelligence'
      path: '/trainer-intelligence'
      fullPath: '/trainer-intelligence'
      preLoaderRoute: typeof AuthenticatedTrainerIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training-capacity': {
      id: '/_authenticated/training-capacity'
      path: '/training-capacity'
      fullPath: '/training-capacity'
      preLoaderRoute: typeof AuthenticatedTrainingCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/$slug': {
      id: '/_authenticated/companies/$slug'
      path: '/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof AuthenticatedCompaniesSlugRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/companies/manage': {
      id: '/_authenticated/companies/manage'
      path: '/manage'
      fullPath: '/companies/manage'
      preLoaderRoute: typeof AuthenticatedCompaniesManageRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
  }
}

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesSlugRoute: typeof AuthenticatedCompaniesSlugRoute
  AuthenticatedCompaniesManageRoute: typeof AuthenticatedCompaniesManageRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesSlugRoute: AuthenticatedCompaniesSlugRoute,
    AuthenticatedCompaniesManageRoute: AuthenticatedCompaniesManageRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademicsRoute: typeof AuthenticatedAcademicsRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedCareerRoute: typeof AuthenticatedCareerRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedCompanySkillDemandRoute: typeof AuthenticatedCompanySkillDemandRoute
  AuthenticatedCourseHealthRoute: typeof AuthenticatedCourseHealthRoute
  AuthenticatedCurriculumAlignmentRoute: typeof AuthenticatedCurriculumAlignmentRoute
  AuthenticatedCurriculumRecommendationsRoute: typeof AuthenticatedCurriculumRecommendationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistrictSkillMapRoute: typeof AuthenticatedDistrictSkillMapRoute
  AuthenticatedDistrictTrainingPlannerRoute: typeof AuthenticatedDistrictTrainingPlannerRoute
  AuthenticatedEmergingSkillsRoute: typeof AuthenticatedEmergingSkillsRoute
  AuthenticatedEmployerValidationRoute: typeof AuthenticatedEmployerValidationRoute
  AuthenticatedIndustrySurveysRoute: typeof AuthenticatedIndustrySurveysRoute
  AuthenticatedInfrastructurePlanningRoute: typeof AuthenticatedInfrastructurePlanningRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedLabourMarketRoute: typeof AuthenticatedLabourMarketRoute
  AuthenticatedLocationDemandRoute: typeof AuthenticatedLocationDemandRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedPlacementFeedbackRoute: typeof AuthenticatedPlacementFeedbackRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQualificationMappingRoute: typeof AuthenticatedQualificationMappingRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedRoleDemandRoute: typeof AuthenticatedRoleDemandRoute
  AuthenticatedSkillIntelligenceRoute: typeof AuthenticatedSkillIntelligenceRoute
  AuthenticatedTrainerIntelligenceRoute: typeof AuthenticatedTrainerIntelligenceRoute
  AuthenticatedTrainingCapacityRoute: typeof AuthenticatedTrainingCapacityRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademicsRoute: AuthenticatedAcademicsRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedCareerRoute: AuthenticatedCareerRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedCompanySkillDemandRoute: AuthenticatedCompanySkillDemandRoute,
  AuthenticatedCourseHealthRoute: AuthenticatedCourseHealthRoute,
  AuthenticatedCurriculumAlignmentRoute: AuthenticatedCurriculumAlignmentRoute,
  AuthenticatedCurriculumRecommendationsRoute:
    AuthenticatedCurriculumRecommendationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistrictSkillMapRoute: AuthenticatedDistrictSkillMapRoute,
  AuthenticatedDistrictTrainingPlannerRoute:
    AuthenticatedDistrictTrainingPlannerRoute,
  AuthenticatedEmergingSkillsRoute: AuthenticatedEmergingSkillsRoute,
  AuthenticatedEmployerValidationRoute: AuthenticatedEmployerValidationRoute,
  AuthenticatedIndustrySurveysRoute: AuthenticatedIndustrySurveysRoute,
  AuthenticatedInfrastructurePlanningRoute:
    AuthenticatedInfrastructurePlanningRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedLabourMarketRoute: AuthenticatedLabourMarketRoute,
  AuthenticatedLocationDemandRoute: AuthenticatedLocationDemandRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedPlacementFeedbackRoute: AuthenticatedPlacementFeedbackRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQualificationMappingRoute:
    AuthenticatedQualificationMappingRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedRoleDemandRoute: AuthenticatedRoleDemandRoute,
  AuthenticatedSkillIntelligenceRoute: AuthenticatedSkillIntelligenceRoute,
  AuthenticatedTrainerIntelligenceRoute: AuthenticatedTrainerIntelligenceRoute,
  AuthenticatedTrainingCapacityRoute: AuthenticatedTrainingCapacityRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
